### ISSUE TITLE
[Content issue]: "Products" should link out to developer microsite

### ISSUE THREAD

**Issue by jinggu-bi** [gobeyondidentity/developer-docs#287]
The home base for CIAM PLG is the developer microsite. The link should be updated from https://www.beyondidentity.com/products/secure-customers to https://www.beyondidentity.com/developers#/mobile

**Comment by patriciamcphee** [comment]
@jinggu-bi I've addressed this issue and it will be merged (published) soon.  You can verify that it's correct at [the preview link](https://developer-docs-git-docs-staging-beyondidentity.vercel.app/).  If you approve, please comment on this issue with `#approved`.  After you've approved it, I will close this issue.

**Comment by jinggu-bi** [comment]
#approved
