### ISSUE TITLE
[Content issue]: Slack needs to be uppercase in the Support section's description on the homepage of the docs

### ISSUE THREAD

**Issue by jinggu-bi** [gobeyondidentity/developer-docs#288]

**Comment by patriciamcphee** [comment]
@jinggu-bi I've addressed this issue and it will be merged (published) soon.  You can verify that it's correct at [the preview link](https://developer-docs-git-docs-staging-beyondidentity.vercel.app/).  If you approve, please comment on this issue with `#approved`.  After you've approved it, I will close this issue.

**Comment by jinggu-bi** [comment]
#approved
