### ISSUE TITLE
[Content issue]: Send Enrollment Emails would be better categorized under Workflows

### ISSUE THREAD

**Issue by jinggu-bi** [gobeyondidentity/developer-docs#289]
One thing is not like the other under "Integration Guides". Unlike the other integration guides, enrollment email send is not a technology that we're integrating with but a workflow that a customer should enable. 

Recommendation to move it to "Workflows"

**Comment by patriciamcphee** [comment]
@jinggu-bi I've addressed this issue and it will be merged (published) soon.  You can verify that it's correct at [the preview link][(https://developer-docs-git-docs-staging-beyondidentity.vercel.app/](https://developer-docs-git-docs-staging-beyondidentity.vercel.app/docs/v1/workflows/send-enrollment)).  If you approve, please comment on this issue with `#approved`.  After you've approved it, I will close this issue.

**Comment by jinggu-bi** [comment]
#approved
