### ISSUE TITLE
[Content issue]: Replace "email" with "Slack" on API documentation homepage

### ISSUE THREAD

**Issue by jinggu-bi** [gobeyondidentity/developer-docs#290]
I like that we have multiple link outs to the developer Slack across the documentation. Keeping with this preferred action, replace the support email with a link to our Slack channel instead on the API overview page https://developer-docs-git-docs-staging-beyondidentity.vercel.app/api/v1

**Comment by patriciamcphee** [comment]
@jinggu-bi I've addressed this issue and it will be merged (published) soon.  You can verify that it's correct at [the preview link](https://developer-docs-git-docs-staging-beyondidentity.vercel.app/api/v1).  If you approve, please comment on this issue with `#approved`.  After you've approved it, I will close this issue.

**Comment by jinggu-bi** [comment]
#approved
